# Pre-Commit Instructions
# - installation: 'pip install pre-commit'
# - activation: 'pre-commit install' (within target directory)
# - running manually: 'pre-commit run --all-files' (within target directory)
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black   # linter, re-formats code (need to re-stage/commit)
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast  # checks if files parse as valid python
      - id: check-case-conflict  # files that would conflict in case-insensitive filesystems
      - id: check-docstring-first  # docstring before code
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]  # required for multi-document .yml files
      - id: detect-private-key
      - id: end-of-file-fixer  # ensure that file is either empty, or ends with one newline
      - id: trailing-whitespace
  - repo: https://github.com/gvanderest/pylama-pre-commit  # static code analysis
    rev: 0.1.2
    hooks:
      - id: pylama
  - repo: https://github.com/PyCQA/bandit  # security checks
    rev: 1.6.2
    hooks:
      - id: bandit
        args: [-ll, --skip, "B101,B501,B104"]
        # B101: Use of assert detected, B501: no SSL validation, B104: binding 0.0.0.0
